name: raygun_cli
description: Command-line tool for Raygun.com
version: 0.0.2
repository: https://github.com/MindscapeHQ/raygun-toolbox/
homepage: https://raygun.com

executables:
  # Ensures the app is installed as "raygun-cli" and not "raygun_cli"
  raygun-cli: 'raygun_cli'

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.4.2
  http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
